version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-vacation
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata-vacation:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vacation-net
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-vacation
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - vacation-net
    depends_on:
      - postgres-db
    restart: always

networks:
  vacation-net:
    driver: bridge

volumes:
  pgdata-vacation:
    driver: local
